apiVersion: v2
publisher: redhat-developer
name: che-workspace-telemetry-woopra-plugin
version: 0.0.2
type: Che Plugin
displayName: Woopra Telemetry Plugin
description: Telemetry plugin to send information to Woopra
title: Che Workspace Telemetry Woopra Plugin
category: Other
spec:
  workspaceEnv:
    - name: CHE_WORKSPACE_TELEMETRY_BACKEND_PORT
      value: '4167'
  containers:
  - name: che-workspace-telemetry-woopra-plugin
    image: quay.io/openshiftio/che-workspace-telemetry-woopra-plugin:latest
    env:
      - name: CHE_API
        value: $(CHE_API_INTERNAL)
      - name: WOOPRA_DOMAIN
        value: ''
      - name: SEGMENT_WRITE_KEY
        value: ''
      - name: WOOPRA_DOMAIN_ENDPOINT
        value: ''
      - name: SEGMENT_WRITE_KEY_ENDPOINT
        value: ''

