## Stage 1 : build with maven builder image with native capabilities
FROM quay.io/quarkus/centos-quarkus-maven:19.2.1 AS build
RUN mkdir -p /tmp/ssl-libs/lib \
  && cp /opt/graalvm/jre/lib/security/cacerts /tmp/ssl-libs \
  && cp /opt/graalvm/jre/lib/amd64/libsunec.so /tmp/ssl-libs/lib/
COPY src /usr/src/app/src
COPY cacerts /tmp/
COPY pom.xml /usr/src/app
COPY settings.xml /usr/src/app
USER root
RUN sed -ie 's#<quarkus.native.additional-build-args>-H:DynamicProxyConfigurationResources=dynamic-proxies.json,--enable-all-security-services</quarkus.native.additional-build-args>#<quarkus.native.additional-build-args>-J-Djavax.net.ssl.trustStore=/tmp/cacerts,-H:DynamicProxyConfigurationResources=dynamic-proxies.json,--enable-all-security-services</quarkus.native.additional-build-args>#g' /usr/src/app/pom.xml 
RUN chown -R quarkus /usr/src/app
USER quarkus
ARG GITHUB_USERNAME 
ARG GITHUB_TOKEN
RUN mvn --settings /usr/src/app/settings.xml -f /usr/src/app/pom.xml -Pnative clean package 

## Stage 2 : create the docker final image
FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY --from=build /usr/src/app/target/*-runner /work/application
COPY --from=build /tmp/ssl-libs/ /work/
COPY --from=build /tmp/cacerts /tmp/
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.log.level=ALL", "-Dquarkus.http.host=0.0.0.0", "-Dquarkus.http.port=${CHE_WORKSPACE_TELEMETRY_BACKEND_PORT}", "-Djava.library.path=/work/lib", "-Djavax.net.ssl.trustStore=/tmp/cacerts"]
