name: woopra-plugin nightly build

on: 
  schedule:
    - cron: '0 0 * * *' # run on the 0th hour at the 0th minute every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          docker build --build-arg GITHUB_USERNAME=${GH_USERNAME} --build-arg GITHUB_TOKEN=${GH_TOKEN} -t quay.io/${ORGANIZATION}/che-workspace-telemetry-woopra-plugin:${TAG} -f src/main/docker/Dockerfile.multi .
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          ORGANIZATION: eclipse
          TAG: nightly
      - name: Log into docker registry
        run: docker login ${REGISTRY} -u ${USERNAME} -p ${PASSWORD}
        env:
          REGISTRY: quay.io
          USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Push image
        run: docker push quay.io/${ORGANIZATION}/che-workspace-telemetry-woopra-plugin:${TAG}
        env:
          ORGANIZATION: eclipse
          TAG: nightly
