name: woopra-plugin PR check

on:
  pull_request:
    branches: [master]

jobs:
  pr_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          docker build --build-arg GITHUB_USERNAME=${GITHUB_USERNAME} --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} -t quay.io/${ORGANIZATION}/che-workspace-telemetry-woopra-plugin:${TAG} -f src/main/docker/Dockerfile.multi .
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME  }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: eclipse
          TAG: pr-check
